### ISSUE TITLE
Definire use case diagram

### ISSUE THREAD

**Issue by itsar19-20** [itsar19-20/quiz#1]

**Comment by kusky33** [comment]
The [use case](https://raw.githubusercontent.com/itsar19-20/quiz/master/docs/UseCase.mdj) has been defined.

**Comment by kusky33** [comment]
The use case is being redefined

**Comment by kusky33** [comment]
[link](https://raw.githubusercontent.com/itsar19-20/quiz/master/docs/UseCase.mdj) to the document
